[package]
name = "rgb_to_spec"
version.workspace = true
edition.workspace = true

[dependencies]
autodiff = { version = "0.7.0" }
color.workspace = true
glam.workspace = true
rand.workspace = true
rayon.workspace = true
