[package]
name = "scene"
version.workspace = true
edition.workspace = true

[dependencies]
color.workspace = true
glam.workspace = true
image = "0.24"
math.workspace = true
spectrum.workspace = true
tobj.workspace = true
util_macros.workspace = true
