[package]
name = "macros"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.101", features = ["full", "extra-traits"] }
quote = "1.0.40"
proc-macro2 = "1.0.95"
