[package]
name = "spectrum"
version.workspace = true
edition.workspace = true

[features]
default = []
fast-analysis = []

[dependencies]
color.workspace = true
glam.workspace = true
math.workspace = true
util_macros.workspace = true
